"""Added and deleted some attributes

Revision ID: 0e7afbc41a16
Revises: 75ac57ddeacc
Create Date: 2018-10-22 10:33:30.377983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e7afbc41a16'
down_revision = '75ac57ddeacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job__offer', sa.Column('contact', sa.String(length=50), nullable=True))
    op.add_column('job__offer', sa.Column('job_type', sa.String(length=100), nullable=True))
    op.drop_column('job__offer', 'title')
    op.add_column('user', sa.Column('edu_background', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'edu_background')
    op.add_column('job__offer', sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('job__offer', 'job_type')
    op.drop_column('job__offer', 'contact')
    # ### end Alembic commands ###
