"""Changed table names

Revision ID: 30265e95b6b0
Revises: 0e7afbc41a16
Create Date: 2018-10-27 20:29:34.284083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30265e95b6b0'
down_revision = '0e7afbc41a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('edu_background', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('JobOffers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_JobOffers_timestamp'), 'JobOffers', ['timestamp'], unique=False)
    op.create_table('JobPosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('salary_price', sa.Integer(), nullable=True),
    sa.Column('salary_category', sa.String(length=5), nullable=True),
    sa.Column('contact_details', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_JobPosts_timestamp'), 'JobPosts', ['timestamp'], unique=False)
    op.drop_index('ix_job__post_timestamp', table_name='job__post')
    op.drop_table('job__post')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('contact_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('edu_background', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_table('job__post',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contact_details', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('salary_category', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('salary_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='job__post_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_job__post_timestamp', 'job__post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_JobPosts_timestamp'), table_name='JobPosts')
    op.drop_table('JobPosts')
    op.drop_index(op.f('ix_JobOffers_timestamp'), table_name='JobOffers')
    op.drop_table('JobOffers')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
