"""empty message

Revision ID: 424528c0d601
Revises: 
Create Date: 2019-01-08 15:49:26.095740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424528c0d601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromUserID', sa.Integer(), nullable=True),
    sa.Column('toUserID', sa.Integer(), nullable=True),
    sa.Column('jobID', sa.Integer(), nullable=True),
    sa.Column('jobTitle', sa.String(length=120), nullable=True),
    sa.Column('content', sa.String(length=1200), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Messages_timeStamp'), 'Messages', ['timeStamp'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('isEmployed', sa.Boolean(), nullable=True),
    sa.Column('image_file', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('Jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('jobType', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.String(length=20), nullable=True),
    sa.Column('postType', sa.String(length=100), nullable=True),
    sa.Column('maxWorker', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Jobs_timeStamp'), 'Jobs', ['timeStamp'], unique=False)
    op.create_table('Works',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('jobID', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('isAccepted', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('working_start_time', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(length=64), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jobID'], ['Jobs.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('userID', 'jobID')
    )
    op.create_index(op.f('ix_Works_timeStamp'), 'Works', ['timeStamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Works_timeStamp'), table_name='Works')
    op.drop_table('Works')
    op.drop_index(op.f('ix_Jobs_timeStamp'), table_name='Jobs')
    op.drop_table('Jobs')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Messages_timeStamp'), table_name='Messages')
    op.drop_table('Messages')
    # ### end Alembic commands ###
