"""empty message

Revision ID: 5bd68d1ec015
Revises: 30265e95b6b0
Create Date: 2018-10-27 20:32:33.537458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd68d1ec015'
down_revision = '30265e95b6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('edu_background', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('JobOffers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_JobOffers_timestamp'), 'JobOffers', ['timestamp'], unique=False)
    op.create_table('JobPosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('salary_price', sa.Integer(), nullable=True),
    sa.Column('salary_category', sa.String(length=5), nullable=True),
    sa.Column('contact_details', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_JobPosts_timestamp'), 'JobPosts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_JobPosts_timestamp'), table_name='JobPosts')
    op.drop_table('JobPosts')
    op.drop_index(op.f('ix_JobOffers_timestamp'), table_name='JobOffers')
    op.drop_table('JobOffers')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
