"""Added attribute @ job_post model

Revision ID: 75ac57ddeacc
Revises: ea6076c3953c
Create Date: 2018-10-18 20:03:54.183040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ac57ddeacc'
down_revision = 'ea6076c3953c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job__post', sa.Column('address', sa.String(length=50), nullable=True))
    op.add_column('job__post', sa.Column('contact_details', sa.String(length=20), nullable=True))
    op.add_column('job__post', sa.Column('salary_category', sa.String(length=5), nullable=True))
    op.add_column('job__post', sa.Column('salary_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job__post', 'salary_price')
    op.drop_column('job__post', 'salary_category')
    op.drop_column('job__post', 'contact_details')
    op.drop_column('job__post', 'address')
    # ### end Alembic commands ###
