"""Job_Post and Job_Offer model

Revision ID: ad8e5b5552be
Revises: 1f40869cb569
Create Date: 2018-10-18 14:46:03.600093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8e5b5552be'
down_revision = '1f40869cb569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job__offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job__offer_timestamp'), 'job__offer', ['timestamp'], unique=False)
    op.add_column('job__post', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job__post', 'title')
    op.drop_index(op.f('ix_job__offer_timestamp'), table_name='job__offer')
    op.drop_table('job__offer')
    # ### end Alembic commands ###
