"""empty message

Revision ID: e557ec64275f
Revises: 
Create Date: 2018-12-01 15:22:53.347971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e557ec64275f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('workExperience', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('isEmployed', sa.Boolean(), nullable=True),
    sa.Column('image_file', sa.String(length=120), nullable=False),
    sa.Column('resumeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resumeId'], ['Resume.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('Jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('jobType', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.String(length=20), nullable=True),
    sa.Column('postType', sa.String(length=100), nullable=True),
    sa.Column('maxWorker', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Jobs_timeStamp'), 'Jobs', ['timeStamp'], unique=False)
    op.create_table('Works',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('jobID', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('isAccepted', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('comments', sa.String(length=64), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jobID'], ['Jobs.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('userID', 'jobID')
    )
    op.create_index(op.f('ix_Works_timeStamp'), 'Works', ['timeStamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Works_timeStamp'), table_name='Works')
    op.drop_table('Works')
    op.drop_index(op.f('ix_Jobs_timeStamp'), table_name='Jobs')
    op.drop_table('Jobs')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_table('Users')
    op.drop_table('Resume')
    # ### end Alembic commands ###
