"""Nullable=False

Revision ID: ea6076c3953c
Revises: ad8e5b5552be
Create Date: 2018-10-18 14:53:59.846319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea6076c3953c'
down_revision = 'ad8e5b5552be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job__offer', sa.Column('title', sa.String(length=100), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('job__offer', 'title')
    # ### end Alembic commands ###
